apiVersion: v1
kind: Pod
metadata:
  name: nodename-demo
spec:
  nodeName: ip-192-168-15-129.ec2.internal
  containers:
    - name: demo
      image: ubuntu:latest 
      command: ["/bin/sh"]
      args: ["-c", "sleep 1000"]