apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: demo-no-execute 
  labels:
    app: nginx 
    env: production 
spec:
  replicas: 4 
  selector:
    matchLabels:
      env : production 
  template :
    metadata :
      labels :
        app : nginx 
        env : production 
    spec :
      tolerations :
        - key : "dedicated" 
          operator : "Equal" 
          value : "special-user" 
          effect : "NoExecute" 
      containers :
        - name : write-container 
          image : alpine 
          command : ["/bin/sh", "-c"] 
          args :
            - |
              while true; do 
                date >> /var/log/index.html; 
                sleep 10; 
              done 
          volumeMounts :
            - name : shared-date-logs 
              mountPath : /var/log 
        - name : container-serving-dates 
          image : nginx 
          ports :
            - containerPort : 80 
          volumeMounts :
            - name : shared-date-logs 
              mountPath : /usr/share/nginx/html 
      volumes :
        - name : shared-date-logs 
          emptyDir : {}  


#kubectl taint nodes ip-192-168-49-125.ec2.internal dedicated=special-user:NOEXECUTE 
# This command applies a taint that not only prevents new pods from being scheduled but also evicts existing pods that do not tolerate the taint.