apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
      - name: fluentd-container
        image: fluent/fluentd:v1.14-1
        ports:
        - containerPort: 24224
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1