apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-required-anti-affinity
  labels:
    app: nginx
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx   
      env: production
  template:
    metadata:
      labels:
        app: nginx
        env: production
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - nginx-25  # Prevents scheduling on nodes with existing 'nginx' pods.
              topologyKey: "kubernetes.io/hostname"  # Ensures they are not on the same node.
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disk-type
                    operator: In
                    values:
                      - ssd 
                      - hdd   
      containers:
        - name: write-container
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                date >> /var/log/index.html;
                sleep 10;
              done
          volumeMounts:
            - name: shared-date-logs
              mountPath: /var/log
        - name: container-serving-dates
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-date-logs
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-date-logs
          emptyDir: {}
