apiVersion: v1
kind: Secret
metadata:
  name: generic-secret
type: Opaque
data:
  USERNAME: YWRtaW4= 
  PASSWORD: dGVzdEAxMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-secret-app
  template:
    metadata:
      labels:
        app: generic-secret-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: generic-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: generic-secret
              key: PASSWORD
