apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::597088042110:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-QIldgp0Ba9Gz
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::597088042110:user/demo
      username: demo
    - userarn: arn:aws:iam::597088042110:user/new-admin  # Replace with the actual IAM user ARN
      username: new-admin  # This is the Kubernetes username for the new admin
      groups:
        - system:masters  # This grants admin privileges to the new user
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

